# Optional: Enable once you have a WakaTime API key in repository secrets as WAKATIME_API_KEY
name: WakaTime weekly dev metrics

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_PROFILE_VIEWS: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "chore: ⏱ update WakaTime weekly dev metrics"
